width: 1920
height: 1080

# less particles, num: 8192 (Recommended)
#grid number: 32
#max timestep: 4
#max hard: 4

## more particles, num: 65536 (Unstable)
grid number: 64
max timestep: 2
max hard: 2.5

# you can only change materials' color
materials:
  - id: 0
    name: WATER
    default color: [0.00, 0.71, 1.0, 1.0]

  - id: 1
    name: BOX
    default color: [0.9,0.9,0.9,0.2]


# set any preset you like
presets:
  - name: DIY_MATERIAL
    material: [ 0 ]
    minimum: [ [ 0.35, 0.35, 0.35 ] ]
    size: [ [ 0.25, 0.25, 0.25 ] ]

  - name: DIY_MATERIAL and SOLID_CUBE
    material: [ 1, 0 ]
    minimum: [ [ 0.30, 0.6, 0.30 ], [ 0.40, 0.25, 0.40 ] ]
    size: [ [ 0.25, 0.25, 0.25 ], [ 0.25, 0.25, 0.25 ] ]